hw = 8

nums = list(range(40, 59 + 1))

first_white = '''........
........
...0....
...00...
...01...
........
........
........
'''

first_black = '''........
........
........
...10...
...01...
........
........
........
'''

for num in nums:
    with open('ffotest/end' + str(num) + '.pos', 'r') as f:
        raw_board = f.readline()
        raw_player = f.readline().split()[0]
        player = '0' if raw_player == 'Black' else '1'
    board = ''
    for i in range(hw):
        for j in range(hw):
            board += '0' if raw_board[i * hw + j] == 'X' else '1' if raw_board[i * hw + j] == 'O' else '.'
        board += '\n'
    stdin = player + '\n'
    if player == '0':
        stdin += first_black
    else:
        stdin += first_white
    stdin += board
    with open('ffotest_proc/' + str(num) + '.txt', 'w') as f:
        f.write(stdin)